import type {
  Boarder,
  PaymentRecord,
  AttendanceSession,
  AttendanceRecord,
  Announcement,
  VisitorEntry,
  Incident,
  MaintenanceReport,
  CurfewRecord,
  WorkshipSchedule,
  BillingSettings,
} from "./types"

// ─── Boarders ────────────────────────────────────────────────────────────────

export const BOARDERS: Boarder[] = [
  {
    id: "1",
    name: "Maria Santos",
    room: "101",
    floor: "1F",
    initials: "MS",
    avatarColor: "#D4C8E8",
    phone: "09171234567",
    email: "maria@email.com",
    joinDate: "Jan 15, 2024",
    monthlyRate: 4500,
    dueDay: 10,
    gracePeriodDays: 3,
    paymentStatus: "paid",
    latePenaltyType: "flat",
    latePenaltyAmount: 200,
    emergencyContact: {
      name: "Juan Santos",
      relationship: "Father",
      phone: "09170001111",
    },
    job: "Nurse",
  },
  {
    id: "2",
    name: "Carlo Reyes",
    room: "102",
    floor: "1F",
    initials: "CR",
    avatarColor: "#B8D4C0",
    phone: "09281234567",
    email: "carlo@email.com",
    joinDate: "Feb 1, 2024",
    monthlyRate: 4500,
    dueDay: 10,
    gracePeriodDays: 3,
    paymentStatus: "paid",
    latePenaltyType: "flat",
    latePenaltyAmount: 200,
    emergencyContact: {
      name: "Ana Reyes",
      relationship: "Mother",
      phone: "09280002222",
    },
    job: "Engineer",
  },
  {
    id: "3",
    name: "Lena Cruz",
    room: "103",
    floor: "1F",
    initials: "LC",
    avatarColor: "#F0C8C8",
    phone: "09391234567",
    email: "lena@email.com",
    joinDate: "Mar 10, 2024",
    monthlyRate: 5000,
    dueDay: 10,
    gracePeriodDays: 3,
    paymentStatus: "overdue",
    latePenaltyType: "flat",
    latePenaltyAmount: 200,
    emergencyContact: {
      name: "Pedro Cruz",
      relationship: "Father",
      phone: "09390003333",
    },
    job: "Teacher",
  },
  {
    id: "4",
    name: "Diego Flores",
    room: "201",
    floor: "2F",
    initials: "DF",
    avatarColor: "#C8D8F0",
    phone: "09171112233",
    email: "diego@email.com",
    joinDate: "Nov 20, 2023",
    monthlyRate: 5000,
    dueDay: 10,
    gracePeriodDays: 3,
    paymentStatus: "pending",
    latePenaltyType: "flat",
    latePenaltyAmount: 200,
    emergencyContact: {
      name: "Rosa Flores",
      relationship: "Mother",
      phone: "09170004444",
    },
    job: "Student",
  },
  {
    id: "5",
    name: "Rina Bautista",
    room: "202",
    floor: "2F",
    initials: "RB",
    avatarColor: "#F0DCC8",
    phone: "09284445566",
    email: "rina@email.com",
    joinDate: "Apr 5, 2024",
    monthlyRate: 4500,
    dueDay: 10,
    gracePeriodDays: 3,
    paymentStatus: "paid",
    latePenaltyType: "percentage",
    latePenaltyAmount: 5,
    emergencyContact: {
      name: "Ben Bautista",
      relationship: "Father",
      phone: "09280005555",
    },
    job: "Call Center",
  },
  {
    id: "6",
    name: "Marco Villanueva",
    room: "203",
    floor: "2F",
    initials: "MV",
    avatarColor: "#D8C8F0",
    phone: "09397778899",
    email: "marco@email.com",
    joinDate: "Jan 8, 2024",
    monthlyRate: 5500,
    dueDay: 10,
    gracePeriodDays: 3,
    paymentStatus: "paid",
    latePenaltyType: "flat",
    latePenaltyAmount: 200,
    emergencyContact: {
      name: "Lisa Villanueva",
      relationship: "Mother",
      phone: "09390006666",
    },
    job: "Architect",
  },
  {
    id: "7",
    name: "Sofia Mendoza",
    room: "301",
    floor: "3F",
    initials: "SM",
    avatarColor: "#C8F0D8",
    phone: "09171002200",
    email: "sofia@email.com",
    joinDate: "May 15, 2024",
    monthlyRate: 5500,
    dueDay: 10,
    gracePeriodDays: 3,
    paymentStatus: "pending",
    latePenaltyType: "flat",
    latePenaltyAmount: 200,
    emergencyContact: {
      name: "Carlos Mendoza",
      relationship: "Father",
      phone: "09170007777",
    },
    job: "Nurse",
  },
  {
    id: "8",
    name: "Jake Aquino",
    room: "302",
    floor: "3F",
    initials: "JA",
    avatarColor: "#F0ECC8",
    phone: "09283003300",
    email: "jake@email.com",
    joinDate: "Jun 1, 2024",
    monthlyRate: 5000,
    dueDay: 10,
    gracePeriodDays: 3,
    paymentStatus: "overdue",
    latePenaltyType: "flat",
    latePenaltyAmount: 200,
    emergencyContact: {
      name: "May Aquino",
      relationship: "Mother",
      phone: "09280008888",
    },
    job: "Driver",
  },
  {
    id: "9",
    name: "Tricia Lim",
    room: "303",
    floor: "3F",
    initials: "TL",
    avatarColor: "#C8F0EC",
    phone: "09394004400",
    email: "tricia@email.com",
    joinDate: "Sep 12, 2023",
    monthlyRate: 4500,
    dueDay: 10,
    gracePeriodDays: 3,
    paymentStatus: "paid",
    latePenaltyType: "flat",
    latePenaltyAmount: 200,
    emergencyContact: {
      name: "James Lim",
      relationship: "Father",
      phone: "09390009999",
    },
    job: "Accountant",
  },
  {
    id: "10",
    name: "Ramon Dela Cruz",
    room: "401",
    floor: "4F",
    initials: "RD",
    avatarColor: "#E8C8F0",
    phone: "09175005500",
    email: "ramon@email.com",
    joinDate: "Jul 20, 2024",
    monthlyRate: 6000,
    dueDay: 10,
    gracePeriodDays: 3,
    paymentStatus: "paid",
    latePenaltyType: "percentage",
    latePenaltyAmount: 5,
    emergencyContact: {
      name: "Grace Dela Cruz",
      relationship: "Spouse",
      phone: "09170010000",
    },
    job: "Manager",
  },
]

export const LOGGED_IN_BOARDER = BOARDERS[3] // Diego Flores — pending

// ─── Payment Records ──────────────────────────────────────────────────────────

export const PAYMENT_RECORDS: PaymentRecord[] = [
  // Sep 2026 — paid
  {
    id: "p1",
    boarderId: "1",
    period: "Sep 2026",
    amount: 4500,
    paidDate: "Sep 3",
    method: "gcash",
    status: "paid",
    receiptStatus: "verified",
    receiptFileName: "gcash_sep3.jpg",
    recordedBy: "boarder",
    verifiedAt: "Sep 3 · 2:10 PM",
    verifiedBy: "Ate Sandra",
  },
  {
    id: "p2",
    boarderId: "2",
    period: "Sep 2026",
    amount: 4500,
    paidDate: "Sep 1",
    method: "bank_transfer",
    status: "paid",
    receiptStatus: "verified",
    receiptFileName: "bdo_sep1.pdf",
    recordedBy: "boarder",
    verifiedAt: "Sep 1 · 4:30 PM",
    verifiedBy: "Ate Sandra",
  },
  {
    id: "p3",
    boarderId: "3",
    period: "Sep 2026",
    amount: 5000,
    paidDate: undefined,
    method: "cash",
    status: "overdue",
    receiptStatus: undefined,
    receiptFileName: undefined,
    recordedBy: "boarder",
  },
  {
    id: "p4",
    boarderId: "4",
    period: "Sep 2026",
    amount: 5000,
    paidDate: undefined,
    method: "gcash",
    status: "pending",
    receiptStatus: "pending_review",
    receiptFileName: "gcash_sep7.jpg",
    recordedBy: "boarder",
  },
  {
    id: "p5",
    boarderId: "5",
    period: "Sep 2026",
    amount: 4500,
    paidDate: "Sep 2",
    method: "gcash",
    status: "paid",
    receiptStatus: "verified",
    receiptFileName: "gcash_sep2.jpg",
    recordedBy: "boarder",
    verifiedAt: "Sep 2 · 11:00 AM",
    verifiedBy: "Ate Sandra",
  },
  {
    id: "p6",
    boarderId: "6",
    period: "Sep 2026",
    amount: 5500,
    paidDate: "Sep 4",
    method: "cash",
    status: "paid",
    receiptStatus: undefined,
    receiptFileName: undefined,
    recordedBy: "guardian",
    notes: "Cash — received in person",
    verifiedBy: "Ate Sandra",
  },
  {
    id: "p7",
    boarderId: "7",
    period: "Sep 2026",
    amount: 5500,
    paidDate: undefined,
    method: "gcash",
    status: "pending",
    receiptStatus: "pending_review",
    receiptFileName: "gcash_sofia.jpg",
    recordedBy: "boarder",
  },
  {
    id: "p8",
    boarderId: "8",
    period: "Sep 2026",
    amount: 5000,
    paidDate: undefined,
    method: "cash",
    status: "overdue",
    receiptStatus: undefined,
    receiptFileName: undefined,
    recordedBy: "boarder",
  },
  {
    id: "p9",
    boarderId: "9",
    period: "Sep 2026",
    amount: 4500,
    paidDate: "Sep 1",
    method: "gcash",
    status: "paid",
    receiptStatus: "verified",
    receiptFileName: "gcash_tricia.jpg",
    recordedBy: "boarder",
    verifiedAt: "Sep 1 · 9:45 AM",
    verifiedBy: "Ate Sandra",
  },
  {
    id: "p10",
    boarderId: "10",
    period: "Sep 2026",
    amount: 6000,
    paidDate: "Sep 5",
    method: "bank_transfer",
    status: "paid",
    receiptStatus: "rejected",
    receiptFileName: "bdo_sep5.pdf",
    recordedBy: "boarder",
    rejectionReason: "Amount mismatch — shows ₱5,500 not ₱6,000",
    verifiedAt: "Sep 5 · 3:00 PM",
    verifiedBy: "Ate Sandra",
  },
  // Aug 2026 — all paid
  {
    id: "p11",
    boarderId: "1",
    period: "Aug 2026",
    amount: 4500,
    paidDate: "Aug 4",
    method: "gcash",
    status: "paid",
    receiptStatus: "verified",
    receiptFileName: "gcash_aug4.jpg",
    recordedBy: "boarder",
    verifiedAt: "Aug 4 · 1:00 PM",
    verifiedBy: "Ate Sandra",
  },
  {
    id: "p12",
    boarderId: "2",
    period: "Aug 2026",
    amount: 4500,
    paidDate: "Aug 3",
    method: "bank_transfer",
    status: "paid",
    receiptStatus: "verified",
    receiptFileName: "bdo_aug3.pdf",
    recordedBy: "boarder",
    verifiedAt: "Aug 3 · 5:00 PM",
    verifiedBy: "Ate Sandra",
  },
  {
    id: "p13",
    boarderId: "3",
    period: "Aug 2026",
    amount: 5000,
    paidDate: "Aug 12",
    method: "cash",
    status: "paid",
    receiptStatus: undefined,
    receiptFileName: undefined,
    recordedBy: "guardian",
    notes: "Cash — late, penalty ₱200 applied",
  },
  {
    id: "p14",
    boarderId: "4",
    period: "Aug 2026",
    amount: 5000,
    paidDate: "Aug 8",
    method: "gcash",
    status: "paid",
    receiptStatus: "verified",
    receiptFileName: "gcash_aug8.jpg",
    recordedBy: "boarder",
    verifiedAt: "Aug 8 · 10:00 AM",
    verifiedBy: "Ate Sandra",
  },
  {
    id: "p15",
    boarderId: "5",
    period: "Aug 2026",
    amount: 4500,
    paidDate: "Aug 2",
    method: "gcash",
    status: "paid",
    receiptStatus: "verified",
    receiptFileName: "gcash_aug2.jpg",
    recordedBy: "boarder",
    verifiedAt: "Aug 2 · 2:00 PM",
    verifiedBy: "Ate Sandra",
  },
  // Jul 2026
  {
    id: "p16",
    boarderId: "4",
    period: "Jul 2026",
    amount: 5000,
    paidDate: "Jul 9",
    method: "gcash",
    status: "paid",
    receiptStatus: "verified",
    receiptFileName: "gcash_jul9.jpg",
    recordedBy: "boarder",
    verifiedAt: "Jul 9 · 3:30 PM",
    verifiedBy: "Ate Sandra",
  },
  {
    id: "p17",
    boarderId: "3",
    period: "Jul 2026",
    amount: 5000,
    paidDate: "Jul 7",
    method: "gcash",
    status: "paid",
    receiptStatus: "verified",
    receiptFileName: "gcash_jul7.jpg",
    recordedBy: "boarder",
    verifiedAt: "Jul 7 · 11:00 AM",
    verifiedBy: "Ate Sandra",
  },
]

// ─── Attendance ───────────────────────────────────────────────────────────────

export const WORSHIP_SCHEDULE: WorkshipSchedule = {
  morningStart: "06:00",
  morningEnd: "08:00",
  morningQRMins: 15,
  eveningStart: "20:00",
  eveningEnd: "22:00",
  eveningQRMins: 15,
  absenceThreshold: 3,
}

export const SESSIONS: AttendanceSession[] = [
  {
    id: "s1",
    type: "morning",
    date: "Sep 7, 2026",
    windowStart: "6:00 AM",
    windowEnd: "8:00 AM",
    qrValidityMins: 15,
  },
  {
    id: "s2",
    type: "evening",
    date: "Sep 7, 2026",
    windowStart: "8:00 PM",
    windowEnd: "10:00 PM",
    qrValidityMins: 15,
  },
  {
    id: "s3",
    type: "morning",
    date: "Sep 6, 2026",
    windowStart: "6:00 AM",
    windowEnd: "8:00 AM",
    qrValidityMins: 15,
  },
  {
    id: "s4",
    type: "evening",
    date: "Sep 6, 2026",
    windowStart: "8:00 PM",
    windowEnd: "10:00 PM",
    qrValidityMins: 15,
  },
  {
    id: "s5",
    type: "morning",
    date: "Sep 5, 2026",
    windowStart: "6:00 AM",
    windowEnd: "8:00 AM",
    qrValidityMins: 15,
  },
  {
    id: "s6",
    type: "evening",
    date: "Sep 5, 2026",
    windowStart: "8:00 PM",
    windowEnd: "10:00 PM",
    qrValidityMins: 15,
  },
  {
    id: "s7",
    type: "morning",
    date: "Sep 4, 2026",
    windowStart: "6:00 AM",
    windowEnd: "8:00 AM",
    qrValidityMins: 15,
  },
  {
    id: "s8",
    type: "evening",
    date: "Sep 4, 2026",
    windowStart: "8:00 PM",
    windowEnd: "10:00 PM",
    qrValidityMins: 15,
  },
]

// present for session s1 (today morning): boarders 1,2,4,5,7,8,9 → absent: 3,6,10
export const ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    id: "a1",
    boarderId: "1",
    sessionId: "s1",
    status: "present",
    checkInTime: "6:14 AM",
    method: "qr",
  },
  {
    id: "a2",
    boarderId: "2",
    sessionId: "s1",
    status: "present",
    checkInTime: "6:22 AM",
    method: "qr",
  },
  {
    id: "a3",
    boarderId: "3",
    sessionId: "s1",
    status: "absent",
    method: "manual",
    overrideReason: "Did not check in — window closed",
    overriddenBy: "Ate Sandra",
  },
  {
    id: "a4",
    boarderId: "4",
    sessionId: "s1",
    status: "present",
    checkInTime: "6:55 AM",
    method: "qr",
  },
  {
    id: "a5",
    boarderId: "5",
    sessionId: "s1",
    status: "present",
    checkInTime: "6:08 AM",
    method: "qr",
  },
  {
    id: "a6",
    boarderId: "6",
    sessionId: "s1",
    status: "absent",
    method: "manual",
    overrideReason: "Informed guardian of medical leave",
    overriddenBy: "Ate Sandra",
  },
  {
    id: "a7",
    boarderId: "7",
    sessionId: "s1",
    status: "present",
    checkInTime: "7:10 AM",
    method: "qr",
  },
  {
    id: "a8",
    boarderId: "8",
    sessionId: "s1",
    status: "present",
    checkInTime: "6:45 AM",
    method: "qr",
  },
  {
    id: "a9",
    boarderId: "9",
    sessionId: "s1",
    status: "present",
    checkInTime: "6:18 AM",
    method: "qr",
  },
  {
    id: "a10",
    boarderId: "10",
    sessionId: "s1",
    status: "absent",
    method: "manual",
    overrideReason: "Night shift — excused",
    overriddenBy: "Ate Sandra",
  },
  // s2 evening — not yet (window not open)
  // s3 yesterday morning
  {
    id: "a11",
    boarderId: "1",
    sessionId: "s3",
    status: "present",
    checkInTime: "6:10 AM",
    method: "qr",
  },
  {
    id: "a12",
    boarderId: "2",
    sessionId: "s3",
    status: "present",
    checkInTime: "6:18 AM",
    method: "qr",
  },
  {
    id: "a13",
    boarderId: "3",
    sessionId: "s3",
    status: "absent",
    method: "manual",
    overrideReason: "Auto-flagged",
    overriddenBy: "System",
  },
  {
    id: "a14",
    boarderId: "4",
    sessionId: "s3",
    status: "absent",
    method: "manual",
    overrideReason: "Auto-flagged",
    overriddenBy: "System",
  },
  {
    id: "a15",
    boarderId: "5",
    sessionId: "s3",
    status: "present",
    checkInTime: "6:05 AM",
    method: "qr",
  },
  {
    id: "a16",
    boarderId: "6",
    sessionId: "s3",
    status: "present",
    checkInTime: "6:42 AM",
    method: "qr",
  },
  {
    id: "a17",
    boarderId: "7",
    sessionId: "s3",
    status: "present",
    checkInTime: "7:01 AM",
    method: "qr",
  },
  {
    id: "a18",
    boarderId: "8",
    sessionId: "s3",
    status: "present",
    checkInTime: "6:28 AM",
    method: "qr",
  },
  {
    id: "a19",
    boarderId: "9",
    sessionId: "s3",
    status: "present",
    checkInTime: "6:12 AM",
    method: "qr",
  },
  {
    id: "a20",
    boarderId: "10",
    sessionId: "s3",
    status: "absent",
    method: "manual",
    overrideReason: "Night shift — excused",
    overriddenBy: "Ate Sandra",
  },
]

// ─── Announcements ────────────────────────────────────────────────────────────

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann1",
    title: "Water shut-off — Sep 9",
    body: "The water supply will be turned off on September 9, 2026 from 8:00 AM to 10:00 AM for scheduled maintenance. Please store water in advance.",
    priority: "normal",
    recipients: "all",
    sentAt: "Sep 6, 2:00 PM",
    sentBy: "Ate Sandra",
    readBy: ["1", "2", "4", "5", "9"],
    acknowledgedBy: [],
  },
  {
    id: "ann2",
    title: "Monthly room inspection — Sep 15",
    body: "Your rooms will be inspected on September 15, 2026. Please ensure rooms are clean and all personal belongings are properly stored. Inspection starts at 9:00 AM.",
    priority: "critical",
    recipients: "all",
    sentAt: "Sep 5, 10:00 AM",
    sentBy: "Ate Sandra",
    readBy: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    acknowledgedBy: ["1", "2", "5", "9", "10"],
  },
  {
    id: "ann3",
    title: "Wifi password changed",
    body: "The boarding house wifi password has been updated. The new password is posted on the main bulletin board near the entrance. Please do not share with non-boarders.",
    priority: "normal",
    recipients: "all",
    sentAt: "Sep 3, 9:00 AM",
    sentBy: "Ate Sandra",
    readBy: ["1", "2", "3", "5", "6", "9"],
    acknowledgedBy: [],
  },
  {
    id: "ann4",
    title: "Curfew reminder — 10:00 PM",
    body: "Please be reminded that house curfew is strictly 10:00 PM every night. Boarders arriving after curfew must notify the guardian in advance. Repeated violations will be subject to penalties per house rules.",
    priority: "critical",
    recipients: ["3", "4", "8"],
    sentAt: "Sep 4, 7:00 PM",
    sentBy: "Ate Sandra",
    readBy: ["4"],
    acknowledgedBy: [],
  },
]

// ─── Visitor Log ─────────────────────────────────────────────────────────────

export const VISITOR_ENTRIES: VisitorEntry[] = [
  {
    id: "v1",
    visitorName: "Jessa Santos",
    boarderId: "1",
    purpose: "Personal visit",
    timeIn: "10:30 AM",
    timeOut: "1:00 PM",
    date: "Sep 7, 2026",
  },
  {
    id: "v2",
    visitorName: "Mr. Reyes Sr.",
    boarderId: "2",
    purpose: "Family visit",
    timeIn: "2:15 PM",
    timeOut: undefined,
    date: "Sep 7, 2026",
  },
  {
    id: "v3",
    visitorName: "Delivery Rider",
    boarderId: "7",
    purpose: "Package pickup",
    timeIn: "3:40 PM",
    timeOut: "3:45 PM",
    date: "Sep 7, 2026",
  },
  {
    id: "v4",
    visitorName: "Ben Cruz",
    boarderId: "3",
    purpose: "Personal visit",
    timeIn: "11:00 AM",
    timeOut: "12:30 PM",
    date: "Sep 6, 2026",
  },
  {
    id: "v5",
    visitorName: "Alma Flores",
    boarderId: "4",
    purpose: "Family visit",
    timeIn: "3:00 PM",
    timeOut: "5:30 PM",
    date: "Sep 5, 2026",
  },
]

// ─── Incidents ────────────────────────────────────────────────────────────────

export const INCIDENTS: Incident[] = [
  {
    id: "i1",
    type: "missed_curfew",
    boarderId: "3",
    title: "Missed Curfew — Lena Cruz",
    description: "Boarded arrived at 11:42 PM. No prior notification.",
    timestamp: "Sep 6 · 11:42 PM",
    resolved: false,
  },
  {
    id: "i2",
    type: "sos",
    boarderId: "8",
    title: "SOS Alert — Jake Aquino",
    description:
      "Boarder triggered emergency alert. Responded: turned out to be accidental.",
    timestamp: "Sep 5 · 9:15 PM",
    resolved: true,
  },
  {
    id: "i3",
    type: "missed_worship",
    boarderId: "4",
    title: "3 Missed Worships — Diego Flores",
    description:
      "Diego has missed 3 consecutive worship sessions. Auto-alert sent.",
    timestamp: "Sep 5 · 9:00 AM",
    resolved: false,
  },
  {
    id: "i4",
    type: "maintenance",
    boarderId: "6",
    title: "A/C Malfunction — Room 203",
    description:
      "Marco reported that the air conditioning unit is not cooling. Technician scheduled.",
    timestamp: "Sep 4 · 7:30 PM",
    resolved: false,
  },
  {
    id: "i5",
    type: "missed_curfew",
    boarderId: "8",
    title: "Missed Curfew — Jake Aquino",
    description: "Boarder arrived at 10:45 PM. Second offense this month.",
    timestamp: "Sep 3 · 10:45 PM",
    resolved: true,
  },
  {
    id: "i6",
    type: "other",
    boarderId: undefined,
    title: "Common Area — Light Fixture",
    description:
      "Hallway light on 3rd floor flickering. Maintenance requested.",
    timestamp: "Sep 2 · 6:00 PM",
    resolved: true,
  },
]

// ─── Maintenance Reports ──────────────────────────────────────────────────────

export const MAINTENANCE_REPORTS: MaintenanceReport[] = [
  {
    id: "m1",
    boarderId: "6",
    room: "203",
    category: "appliance",
    description:
      "Air conditioning unit not cooling. Room temperature stays warm even at max settings.",
    status: "in_progress",
    submittedAt: "Sep 4, 7:30 PM",
  },
  {
    id: "m2",
    boarderId: "3",
    room: "103",
    category: "plumbing",
    description:
      "Bathroom faucet leaking slowly. Water dripping continuously from the handle.",
    status: "open",
    submittedAt: "Sep 5, 8:00 AM",
  },
  {
    id: "m3",
    boarderId: "8",
    room: "302",
    category: "furniture",
    description:
      "Door lock is loose and does not latch properly. Requires tightening or replacement.",
    status: "resolved",
    submittedAt: "Aug 28, 10:00 AM",
    resolvedAt: "Aug 30, 2:00 PM",
  },
  {
    id: "m4",
    boarderId: "10",
    room: "401",
    category: "electrical",
    description:
      "Main light fixture flickers every few seconds. Possibly a loose bulb or wiring issue.",
    status: "open",
    submittedAt: "Sep 2, 6:00 PM",
  },
]

// ─── Curfew Records ───────────────────────────────────────────────────────────

export const CURFEW_RECORDS: CurfewRecord[] = [
  {
    id: "c1",
    boarderId: "1",
    date: "Sep 7, 2026",
    curfewTime: "10:00 PM",
    checkedInAt: "9:15 PM",
    status: "compliant",
  },
  {
    id: "c2",
    boarderId: "2",
    date: "Sep 7, 2026",
    curfewTime: "10:00 PM",
    checkedInAt: "8:30 PM",
    status: "compliant",
  },
  {
    id: "c3",
    boarderId: "3",
    date: "Sep 7, 2026",
    curfewTime: "10:00 PM",
    checkedInAt: undefined,
    status: "pending",
  },
  {
    id: "c4",
    boarderId: "4",
    date: "Sep 7, 2026",
    curfewTime: "10:00 PM",
    checkedInAt: "9:50 PM",
    status: "compliant",
  },
  {
    id: "c5",
    boarderId: "5",
    date: "Sep 7, 2026",
    curfewTime: "10:00 PM",
    checkedInAt: "7:00 PM",
    status: "compliant",
  },
  {
    id: "c6",
    boarderId: "6",
    date: "Sep 7, 2026",
    curfewTime: "10:00 PM",
    checkedInAt: "9:00 PM",
    status: "compliant",
  },
  {
    id: "c7",
    boarderId: "7",
    date: "Sep 7, 2026",
    curfewTime: "10:00 PM",
    checkedInAt: undefined,
    status: "pending",
  },
  {
    id: "c8",
    boarderId: "8",
    date: "Sep 7, 2026",
    curfewTime: "10:00 PM",
    checkedInAt: "10:48 PM",
    status: "late",
  },
  {
    id: "c9",
    boarderId: "9",
    date: "Sep 7, 2026",
    curfewTime: "10:00 PM",
    checkedInAt: "8:45 PM",
    status: "compliant",
  },
  {
    id: "c10",
    boarderId: "10",
    date: "Sep 7, 2026",
    curfewTime: "10:00 PM",
    checkedInAt: undefined,
    status: "absent",
  },
]

// ─── Default Settings ─────────────────────────────────────────────────────────

export const DEFAULT_BILLING: BillingSettings = {
  dueDay: 10,
  gracePeriodDays: 3,
  penaltyType: "flat",
  penaltyAmount: 200,
  reminders: {
    before3: true,
    before1: true,
    onDay: false,
    after1: true,
    after3: true,
  },
  channels: { inApp: true, sms: false, email: false },
}
